### ISSUE TITLE
Thumbnail does not display on transferred filespacepage

### ISSUE THREAD

**Issue by anderson13g** [enterprisemediawiki/MezaExt#13]
![Thumbnail Issue Screenshot](https://user-images.githubusercontent.com/31141811/64738354-99bccd80-d4b4-11e9-860c-e3120b76d6df.PNG)

The original file is fine, however and calling the file on a mainspace page results in the file displaying correctly.

**Comment by anderson13g** [comment]
Several more files couldn't not display the thumbnail following a transfer. When i attempted to load the same file as a new version of the file to the ISS wiki, the following errors were displayed:

> Upload error
> Could not read or write file "`mwstore://local-backend/local-public/c/c1/Yury_Seryakov.jpg`" due to insufficient permissions or missing directories/containers.
> 
> Could not store file "`/tmp/phpEVnvzw" at "mwstore://local-backend/local-public/c/c1/Yury_Seryakov.jpg`".

When i deleted the page. although it was succuessful, the following erros appeared:

> Error deleting file: Yury Seryakov.jpg
> 
> Errors were encountered while deleting the file:
> Could not read or write file "`mwstore://local-backend/local-deleted/l/q/x/lqxrv0doj7bkkyaazew0xvzkionjrwv.jpg`" due to insufficient permissions or missing directories/containers.
> Could not move file "`mwstore://local-backend/local-public/c/c1/Yury_Seryakov.jpg`" to "`mwstore://local-backend/local-deleted/l/q/x/lqxrv0doj7bkkyaazew0xvzkionjrwv.jpg`".
> Yury Seryakov.jpg has been deleted.

**Comment by anderson13g** [comment]
Related Commit link [Apache cannot write to /opt/data-meza/tmp. For Special:TransferPages, it
is necessary for Apache to write a temp file, which then is picked up by
the MW job queue and executed as user meza-ansible.](https://github.com/enterprisemediawiki/meza/commit/1f130079f2b9fafe255be58f8814a9706be51d9a)

`[744ffb7aa0ae007a56fca290] [no req]   LocalFileLockError from line 2251 of /opt/htdocs/mediawiki/includes/filerepo/file/LocalFile.php: Could not open lock file for "mwstore&#58;//local-backend/local-public/e/e4/Alexander_Muzyka.JPG". Make sure your upload directory is configured correctly and your web server has permission to write to that directory. See https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgUploadDirectory for more information.
Backtrace:
#0 /opt/htdocs/mediawiki/includes/filerepo/file/LocalFile.php(1346): LocalFile->lock()
#1 /opt/htdocs/mediawiki/includes/import/ImportableUploadRevisionImporter.php(104): LocalFile->upload(string, string, string, integer, array, string, User)
#2 /opt/htdocs/mediawiki/includes/import/WikiRevision.php(659): ImportableUploadRevisionImporter->import(WikiRevision)
#3 [internal function]: WikiRevision->importUpload()
#4 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(3191): call_user_func_array(array, array)
#5 /opt/htdocs/mediawiki/maintenance/importDump.php(218): Wikimedia\Rdbms\Database->deadlockLoop(array)
#6 /opt/htdocs/mediawiki/includes/import/WikiImporter.php(1049): BackupReader->handleUpload(WikiRevision)
#7 /opt/htdocs/mediawiki/includes/import/WikiImporter.php(997): WikiImporter->processUpload(array, array)
#8 /opt/htdocs/mediawiki/includes/import/WikiImporter.php(803): WikiImporter->handleUpload(array)
#9 /opt/htdocs/mediawiki/includes/import/WikiImporter.php(608): WikiImporter->handlePage()
#10 /opt/htdocs/mediawiki/maintenance/importDump.php(345): WikiImporter->doImport()
#11 /opt/htdocs/mediawiki/maintenance/importDump.php(287): BackupReader->importFromHandle(resource)
#12 /opt/htdocs/mediawiki/maintenance/importDump.php(116): BackupReader->importFromStdin()
#13 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(94): BackupReader->execute()
#14 /opt/htdocs/mediawiki/maintenance/importDump.php(350): require_once(string)
#15 {main}
2019-12-02 22:21:17: wiki_hsg (ID 2229) 1 pages (2.9|2.9/sec all|curr), 1 revs (2.9|2.9/sec all|curr), ETA 2019-12-03 01:24:15 [max 31432]
upload: Alexander_Matrosov.jpg
PHP Warning:  XMLReader::open(): Unable to open source data in /opt/htdocs/mediawiki/includes/libs/mime/XmlTypeCheck.php on line 158`

Ok, so to restate the problem so i can write an issue on GitHub:
 

The `ansible-user` that executed the transfer pages job did not have permission to write to the `uploads` folder because it was a member of the group. Occassionally, 1-off file transfers or the first file are run outside of jobs, in which the `Apache` owner wrote to the directory successfuly b/c it had permission.
 
 
Transferring files worked on INT and DEV b/c a recurrsive permissions loops in xyz file gave ansible-user the correct permissions.
 
The issue was fixed b/c SSHing in. However, the xyz file should be updated to give `ansible-user` the correct permissions. which file was it again? https://github.com/enterprisemediawiki/meza/tree/master/src/roles
